runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "myangular"

handlers:
- url: /
  static_files: dist/hw8/index.html
  upload: dist/hw8/index.html

- url: /
  static_dir: dist/hw8